name: Frontend CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh-keyscan -H 37.187.92.116 >> ~/.ssh/known_hosts
        ssh-agent bash -c 'ssh-add ~/.ssh/deploy_key; ssh -o StrictHostKeyChecking=no ubuntu@37.187.92.116 bash -s' << 'EOF'
          if [ ! -d /home/ubuntu/lolpeaks-front ]; then
            git clone git@github.com:mlinaresweb/LolPeaks-Front.git /home/ubuntu/lolpeaks-front
          fi
          cd /home/ubuntu/lolpeaks-front/
          git fetch origin main
          git reset --hard origin/main
          # npm install
          # npm run build
          # Si estás usando un servidor como nginx para servir tu frontend, reinícialo
          # sudo systemctl restart nginx
        EOF
