name: Frontend CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh-keyscan -H 37.187.92.116 >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/deploy_key ubuntu@37.187.92.116 'bash -s' << 'EOF'
          cd /home/ubuntu/lolpeaks-front/
          git fetch origin main
          git reset --hard origin/main
          npm install
          npm run build
          # Si estás usando un servidor como nginx para servir tu frontend, reinícialo
          # sudo systemctl restart nginx
        EOF
